apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.container.image }}
        env:
        - name: MY_SECRET
          valueFrom: 
            secretKeyRef:
              name: {{.Values.name }}
              key: some_confidential_text
        - name: MY_CONFIGMAP
          valueFrom:
            configMapKeyRef:
              name: {{.Values.name }}
              key: some_non_confidential_data
        ports:
        - containerPort: 8086
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8086
            httpHeaders:
            - name: Accept
              value: ""
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8086
            httpHeaders:
            - name: Accept
              value: ""
          initialDelaySeconds: 15
          periodSeconds: 5
          terminationGracePeriodSeconds: 40
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"